apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-persistence-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: share-volume