apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-volume
  # The label is used for matching the exact claim
  labels:
    usage: share-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: minecraftdata
    readOnly: false
  mountOptions:
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl