apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-persistence-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi