apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp   
    spec:
      containers:
      - name: web
        image: dockerdemos/lab-web
        ports:
         - containerPort: 80
           name: http
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapp